excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://JerryYip88.github.io
title: Awesome
email: ipjerry88@outlook.com
author: JerryYip88
description: My awesome new site
paginate: 3
google_analytics: 